language: go

go:
  - "1.11.x"

go_import_path: algorithms

install:
  - go get -t -v ./...

script:
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
    - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
