language: go

go:
  - "1.11.x"
  - master

go_import_path: op

install:
  - go get -t -v ./...  # default install

script:
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
    - codecov
