language: go

go:
  - "1.11.x"
  - master

before_install:
  - go get -t -v ./...

script:
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
    - bash <(curl -s https://codecov.io/bash)


language: python3

python3:
  - "3.5.1"

script:
  - python3 -m unittest
